namespace: cremsburg
name: apstra
version: 0.1.0
readme: README.md
authors:
- Calvin Remsburg <cremsburg@protonmail.com>
description: Ansible collection for Juniper's Apstra solution
license:
- GPL-2.0-or-later
license_file: ''
tags: 
    - networking
    - datacenter
    - juniper
    - apstra
    - aos
dependencies: {}
repository: https://gitlab.com/_calvinr/networking/apstra-ansible-collection
documentation: https://gitlab.com/_calvinr/networking/apstra-ansible-collection/-/tree/master/cremsburg/apstra
homepage: https://gitlab.com/_calvinr/networking/apstra-ansible-collection/-/tree/master/cremsburg/apstra
issues: https://gitlab.com/_calvinr/networking/apstra-ansible-collection/-/issues
build_ignore:
- tests
- '*.tar.gz'
